apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-dotnet
  namespace: kube-system
data:
  parse-dotnet-log-field.conf: |
    <filter kubernetes.var.log.containers.*dotnet*>
      @type parser
      key_name log
      reserve_time true
      <parse>
        @type json
      </parse>
    </filter>
